services:
  web:
    container_name: secureshare
    build: .
    ports:
      - "5200:5200"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_RUN_HOST=0.0.0.0
    command: python run.py
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    container_name: secureshare_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge